version: 2

build:
  os: "ubuntu-24.04"
  tools:
    python: "3.11"
  commands:
    - pip install uv
    - uv pip install --system tox-uv
    - tox -e docs
    - mkdir -p $READTHEDOCS_OUTPUT/html
    - cp -av docs/build/html/ $READTHEDOCS_OUTPUT
